In [13]:

import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# data loading by using keras
training_set = tf.keras.utils.image_dataset_from_directory(
    'train masking',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)
validation_set = tf.keras.utils.image_dataset_from_directory(
    'validation Masking',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)
for x,y in training_set:
    print (x , x.shape)
    print(y , y.shape)
    break
# building model

from tensorflow.keras.layers import Dense , Conv2D , MaxPool2D , Flatten
from tensorflow.keras.models import Sequential
model = Sequential()
model.add(Conv2D(filters=32,kernel_size=3,padding='same' , activation='relu', input_shape=[128, 128 , 3])) # rectified linear unit
model.add(Conv2D(filters=32,kernel_size=3,padding='same' , activation='relu'))
model.add(MaxPool2D(pool_size=2 , strides=2))
model.add(Conv2D(filters=64,kernel_size=3,padding='same' , activation='relu', input_shape=[128, 128 , 3]))
model.add(Conv2D(filters=64,kernel_size=3,padding='same' , activation='relu'))
model.add(MaxPool2D(pool_size=2 , strides=2))
model.add(Conv2D(filters=128,kernel_size=3,padding='same' , activation='relu', input_shape=[128, 128 , 3]))
model.add(Conv2D(filters=128,kernel_size=3,padding='same' , activation='relu'))
model.add(MaxPool2D(pool_size=2 , strides=2))
model.add(Conv2D(filters=256,kernel_size=3,padding='same' , activation='relu', input_shape=[128, 128 , 3]))
model.add(Conv2D(filters=256,kernel_size=3,padding='same' , activation='relu'))
model.add(MaxPool2D(pool_size=2 , strides=2))
# flattenig operation
model.add(Flatten())

model.add(Dense(units=1024,activation='relu'))
# output layer
model.add(Dense(units=16 , activation='softmax'))
# compiling model 
model.compile(optimizer='adam' , loss='categorical_crossentropy',metrics=['accuracy'])
# model training
training_model=model.fit(x=training_set,validation_data=validation_set,epochs=10)

Found 29156 files belonging to 16 classes.
Found 5466 files belonging to 16 classes.
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
  